version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development  
    volumes:
      - .:/usr/src/app  

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000" 
    environment:
      - DB_NAME=Customers
